### ISSUE TITLE
Whether C17 is supported?

### ISSUE THREAD

**Issue by HH45137** [GPUOpen-LibrariesAndSDKs/FidelityFX-SDK#10]
Whether **C17** is supported?
I want to use the SDK for the C project

**Comment by jlacroixAMD** [comment]
The SDK code itself (everything under /sdk) should all be C99. Samples and Framework showcasing the effects are using C++11. You should have no issues pulling the SDK into a C++17 project.

**Comment by HH45137** [comment]
> SDK代码本身（/sdk下的所有内容）都应该是C99。展示效果的示例和框架使用 C++11。将 SDK 拖入 C++17 项目应该不会有任何问题。

Thank you ☺️
