### ISSUE TITLE
Is there an easy way to integrate it into an API-agnostic RHI layer?

### ISSUE THREAD

**Issue by ohmaya** [GPUOpen-LibrariesAndSDKs/FidelityFX-SDK#14]
As we know, Cauldron's generated project is either DX12 or Vulkan, which is selectable as Visual Studio build configuration.

An engine's binary might contains various APIs which is selectable via launch command line flag at runtime.

Thanks.

**Comment by ohmaya** [comment]
"implement your own backend for other platforms
/// which sit on top of your engine's own abstraction layer"
?

**Comment by rys** [comment]
That's right, the modular backend support is the path to using FidelityFX technology with an application's own graphics abstraction, if it isn't using Vulkan or DX12 directly.

**Comment by ohmaya** [comment]
Sorry, the 2nd message, "on top of your engine's own abstraction layer", is somewhat another issue.

By looking at UE and other engine's integrations, I find they call FSR DX12 functions (ffxFsr2GetScratchMemorySizeDX12) directly in RHI DX12, so no need for those functions in API-agnostic RHI (ffxGetInterface).
