### ISSUE TITLE
Very good job!!! 

### ISSUE THREAD

**Issue by HH45137** [GPUOpen-LibrariesAndSDKs/FidelityFX-SDK#18]
AMD YES!!!

**Comment by HH45137** [comment]
so fsr3 is have support mali GPU a plan?

**Comment by rys** [comment]
There is no specific support for any particular GPU architecture in FSR3. There is only support for DX12 on Windows today, which is a limitation for any GPU that doesn't support that OS and graphics API, but the technology is GPU architecture agnostic as long as the minimum shader level features are met.
