### ISSUE TITLE
Is it possible to (relatively) easy patch parallel sort to support 64-bit keys?

### ISSUE THREAD

**Issue by s1ddok** [GPUOpen-LibrariesAndSDKs/FidelityFX-SDK#3]
I need to sort 64 bit UINTs and I wonder if I can patch current implementation in a reasonable time? Could you give me some guidance?

**Comment by jlacroixAMD** [comment]
Yes, it should be easily supportable. You'll have to change the binding of the key buffer to uint64_t, and increase the number of passes you are executing (from 8 to 16). Also, as reading 64-bit entries can be slower, for the sum pass, I would recommend binding your 64-bit buffer as 32-bit UINT, and then reading every other value (be sure to mind if you are reading the low bits or high bits), and only operate on that to keep read costs down. When doing the scatter you'll have no choice but to do the full 64-bits which will be a bit slower.
