### ISSUE TITLE
FrameinterpolationSwapchainDX12 doesn't support BGRA8 swapchain/backbuffer formats

### ISSUE THREAD

**Issue by Nukem9** [GPUOpen-LibrariesAndSDKs/FidelityFX-SDK#36]
This is half bug, half feature request.

When a BGRA8 swap chain desc is passed to `ffxCreateFrameinterpolationSwapchainDX12`, `GetFfxSurfaceFormat` or `ffxGetSurfaceFormatDX12` are called at some point and trip an assertion due to the lack of backend support. Under certain circumstances the code crashes. I didn't see this stated in the documentation anywhere. I could be blind though.

I implemented a workaround by adding relevant formats to the [FfxSurfaceFormat enum](https://github.com/GPUOpen-LibrariesAndSDKs/FidelityFX-SDK/blob/a0632abf1350bb64c098573d84c42f053f053a6e/sdk/include/FidelityFX/host/ffx_types.h#L230) and adding more switch cases.

**Comment by jlacroixAMD** [comment]
Can I get a list of all missing surface formats you'd like to also be supported?

Thanks,

Jason

**Comment by jlacroixAMD** [comment]
I've added the formats to a local branch. They should appear in the next public release of the SDK.

Thanks,

Jason
