### ISSUE TITLE
[Feature request] GPU-driven numKeysToSort in Parallel Sort

### ISSUE THREAD

**Issue by s1ddok** [GPUOpen-LibrariesAndSDKs/FidelityFX-SDK#4]
It will be nice if number of sorting keys could be provided without CPU/GPU sync, for example by supplying 4 bytes long refrerence to a GPU buffer that should contain the target number of keys. Currently it is impossible to sort arbitrary number of GPU-generated objects without making a CPU sync.

**Comment by jlacroixAMD** [comment]
If you have a look at the GPUParticle RenderModule which is used in the FSR sample, there is a manual setup to do this you can replicate for the time being. This will be added as an option for a future version of the SDK.

**Comment by s1ddok** [comment]
@jlacroixAMD thank you for the reply, but I'm not sure what you mean by that, as far as I can see the number of keys to sort is still being applied from CPU side

https://github.com/GPUOpen-LibrariesAndSDKs/FidelityFX-SDK/blob/d7531ae47d8b36a5d4025663e731a47a38be882f/samples/parallelsort/parallelsortrendermodule.cpp#L254
