### ISSUE TITLE
Failed to get media bundle information from server

### ISSUE THREAD

**Issue by Andraw-sue** [GPUOpen-LibrariesAndSDKs/FidelityFX-SDK#7]
D:\Code\FidelityFX-SDK-main-fsr1\FidelityFX-SDK-main>UpdateMedia.bat
Default bundle SHA-256: 48f8b87302950208cfea7619a03235a448b913d4e4836422714696192ae1511f
SDK root: D:\Code\FidelityFX-SDK-main-fsr1\FidelityFX-SDK-main\

AMD FidelityFX Media Delivery System
Failed to get bundle information from server (SHA256: 48f8b87302950208cfea7619a03235a448b913d4e4836422714696192ae1511f)

OR

D:\Code\FidelityFX-SDK-main-fsr1\FidelityFX-SDK-main\sdk\tools\media_delivery>MediaDelivery.exe -latest
AMD FidelityFX Media Delivery System
Failed to get latest media bundle information from server

**Comment by ctgriffiths** [comment]
I haven’t been able to reproduce this, maybe this was an intermittent network failure?

The media delivery tool makes a https request for a zip file and extracts it to the ./media directory. Is there something about your setup that would block that https request?

As an alternative you can download the prebuilt package from GPUOpen which includes the media:
https://gpuopen.com/amd-fidelityfx-sdk/#download

**Comment by ShaoyuanLi** [comment]
It looks like Pre-Built’s SDK also doesn’t include media files 
https://gpuopen.com/FidelityFX_download.php
