### ISSUE TITLE
In FSR sample, missing "ffx_fsr2_force16_begin.h" and "ffx_fsr2_force16_end.h"?

### ISSUE THREAD

**Issue by SergioAlapontARM** [GPUOpen-LibrariesAndSDKs/FidelityFX-SDK#8]
In **[ffx_fsr2_upsample.h](https://github.com/GPUOpen-LibrariesAndSDKs/FidelityFX-SDK/blob/main/sdk/include/FidelityFX/gpu/fsr2/ffx_fsr2_upsample.h)**, looks like this is a path not compiled by the SDK (I don't see anything enabling FFX_FSR2_OPTION_UPSAMPLE_SAMPLERS_USE_DATA_HALF anyway) but, looks like these files are currently missing from the SDK's repository.

![image](https://github.com/GPUOpen-LibrariesAndSDKs/FidelityFX-SDK/assets/53938158/65963934-0709-4298-86c8-0a6d5ea00c56)

Unless I'm missing something here ...

**Comment by g-exp** [comment]
+1 suspect those files are for test

**Comment by rys** [comment]
Well spotted, we'll look at removing that unused upsampling FP16 path in a future release. I've filed a corresponding issue in our internal bug tracker.
