### ISSUE TITLE
FFX API is AMD's version of Nvidia Streamline?

### ISSUE THREAD

**Issue by QDanteQ** [GPUOpen-LibrariesAndSDKs/FidelityFX-SDK#80]
Hello, in docs I see you mention that we **have to** use FFX API for FSR3 FG. Is it mandatory, or can we use FFX SDK directly, as it was for FSR 3.0? What are advantages of FFX API?
Thank you for your work.

**Comment by HerveRV** [comment]
In my understanding, yes, it's mandatory. Just use the SDK, in version 1.1 they explain here : https://gpuopen.com/presentations/2024/FidelityFX_Super_Resolution_3-1_Release-Overview_and_Integration.pdf
page 10 : 
```

FSR3 consists of 3 separate systems:
• Upscale
• Frame Generation
• Frame Pacing/Swapchain
• With the FidelityFX API, these systems need created separately and held in a context.
• Creating the context, configuring them, and dispatching them will result in the effect providing desired
results
• Individual contexts will have rules guiding where and when in the graphics pipeline configure and dispatch
operations are valid.
```

**Comment by QDanteQ** [comment]
FFX API is using FFX SDK under the hood. So theoretically we can try to use FFX SDK directly, without FFX API. But from my tests, they broke FSR3Context and manually managing FrameInterpolation, OpticalFlow and others contexts sometimes looks too intrusive.
